FROM php:7.4-fpm-alpine

EXPOSE 9000

WORKDIR /var/www/html

RUN apk --update --no-cache add \
    bash \
    ca-certificates \
    curl \
    openssl \
    nodejs \
    npm \
    build-base \
    autoconf \
    curl-dev \
    && pecl install mongodb redis \
    && docker-php-ext-enable mongodb redis \
    && pecl config-set php_ini /etc/php.ini \
    && docker-php-ext-install pdo pdo_mysql \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && rm -rf /var/cache/apk/*

COPY ./docker/php-fpm/php-ini-overrides.ini $PHP_INI_DIR/conf.d/99-overrides.ini
COPY ./docker/php-fpm/docker-entrypoint-dev.sh /usr/local/bin/docker-entrypoint.sh

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["php-fpm"]